# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180530_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='summarry',
            field=models.CharField(default='some book', max_length=500),
        ),
    ]
