# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_books_summarry'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('book_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pick up', max_length=50)),
                ('issue_date', models.DateTimeField(default=datetime.datetime(2018, 7, 24, 10, 57, 12, 852806))),
                ('return_date', models.DateTimeField(default=datetime.datetime(2018, 7, 31, 10, 57, 12, 852829))),
            ],
        ),
    ]
