# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 13:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180728_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 28, 13, 44, 39, 386244)),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 28, 13, 44, 39, 386268)),
        ),
    ]
